# Generated by Django 4.2.6 on 2023-11-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElecDeals', '0004_feature_remove_gadget_item_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAM', models.CharField(blank=True, max_length=50)),
                ('ROM', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='gadget',
            name='item_capacity',
        ),
        migrations.RemoveField(
            model_name='gadget',
            name='item_type',
        ),
        migrations.AddField(
            model_name='gadget',
            name='item_capacity',
            field=models.ManyToManyField(blank=True, related_name='gadgets', to='ElecDeals.capacity'),
        ),
        migrations.AddField(
            model_name='gadget',
            name='item_type',
            field=models.ManyToManyField(related_name='gadgets', to='ElecDeals.type'),
        ),
    ]
