# Generated by Django 4.2.6 on 2023-11-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElecDeals', '0005_capacity_type_remove_gadget_item_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacity',
            options={'verbose_name_plural': 'capacity'},
        ),
    ]
